# 1.2: NumPy

The fundamental type of variable that NumPy is built around is called an array. These are a lot like lists, but NumPy is optimised to perform mathematical operations on arrays of numbers. This means that some operations are much faster or more convenient using NumPy. Arrays are intended to represent mathematical vectors, matrices and tensors, and NumPy provides many of the mathematical operations we might perform on them.

It is standard to import NumPy as `np`:

In [32]:
import numpy as np

## Creating NumPy arrays

A NumPy array can be created using the method `array`:

In [33]:
x=np.array([1,2,3])

NumPy supports the creation of multi-dimensional arrays, for example the following code creates a matrix with 3 rows and 2 columns:

In [34]:
y=np.array([[1,2],[1,2],[1,2]])
y

array([[1, 2],
       [1, 2],
       [1, 2]])

Here the outer square brackets correspond to the rows and the inner square brackets correspond to the columns. It is also possible to have higher dimensional arrays, but we won't deal with these much in this notebook.

Unlike lists, NumPy arrays are designed to be rectangular (all rows must have the same number of elements). 

If we try to create an array with rows of different lengths, NumPy cannot form a proper 2D array. Instead, it creates an array of objects and raises a `ValueError`or a warning depending on which NumPy version is running on your machine:

In [36]:
np.array([[1,2,3],[1,2]])

<ipython-input-36-59205dbef6a2>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,2,3],[1,2]])


array([list([1, 2, 3]), list([1, 2])], dtype=object)

Restricting to rectangular arrays is one of the reasons that some operations on arrays can be faster than on lists. If you need to have non-rectangular arrays, then you might reconsider the data structure that you're using, or whether you can use zero to represent empty entries in an array, or you may need to rethink using NumPy.

We can obtain information about the shape of the array using the `shape` attribute:

In [ ]:
y.shape

(3, 2)

This tells us that the variable `y` has 3 rows and 2 columns. The shape of the `x` variable is

In [ ]:
x.shape

(3,)

This tells us that `x` is one-dimensional, but note that its size is not (3,1). NumPy usually runs faster on such one-dimensional arrays, rather than forcing them to be row or column vectors.

In [ ]:
# You could force your variable to be a row vector:
x=np.array([[1,2,3]])
x.shape
# But doing so may make your code slower.

(1, 3)

The `size` attribute tells us how many elements there are in the array

In [ ]:
x.size

3

In [ ]:
y.size

6

## Data types (`dtype`)

Every NumPy array has a **data type** (`dtype`) that determines what kind of values it stores and how much memory each element uses. NumPy infers the dtype automatically, but you can also specify it explicitly.

Common dtypes you will encounter:

| dtype | Description | Memory per element |
|---|---|---|
| `float64` | 64-bit floating point (NumPy default for floats) | 8 bytes |
| `float32` | 32-bit floating point | 4 bytes |
| `int64` | 64-bit integer (common default on most systems) | 8 bytes |
| `int32` | 32-bit integer | 4 bytes |
| `bool` | Boolean (True/False) | 1 byte |

You can inspect the dtype of any array using the `.dtype` attribute:

In [ ]:
a = np.array([1.0, 2.0, 3.0])
print(a.dtype)   # float64 — consistent across platforms

b = np.array([1, 2, 3])
print(b.dtype)   # int64 on Linux/macOS, int32 on Windows

float64
int32


You can specify the dtype explicitly at creation time:

In [ ]:
# Create a float32 array to save memory (useful with large datasets)
a_f32 = np.array([1.0, 2.0, 3.0], dtype=np.float32)
print(a_f32.dtype)

# Decimal parts are truncated, not rounded, when casting to int
a_int = np.array([1.0, 2.5, 3.7], dtype=np.int32)
print(a_int)
print(a_int.dtype)

float32
[1 2 3]
int32


You can convert (cast) an array to a different dtype using `.astype()`:

In [ ]:
b = np.array([1, 2, 3])
b_float = b.astype(np.float64)
print(b_float)
print(b_float.dtype)

[1. 2. 3.]
float64


**Why does dtype matter?**

- `float32` uses half the memory of `float64`. For large arrays this can be the difference between fitting in memory or not.
- Integer division behaves differently from float division: make sure your array has the right type before dividing.
- Many machine learning libraries (e.g. PyTorch, scikit-learn) expect specific dtypes and will raise errors or silently convert if given the wrong one.

Check `.dtype` whenever an array is not behaving as expected.

A common operation on vectors and matrices is to transpose them, i.e. reflect them along the diagonal. This can be achieved in NumPy using the method

In [ ]:
y.T

array([[1, 1, 1],
       [2, 2, 2]])

Usually the arrays that we want to use will be much too big to define by hand, so there are built in methods to define arrays. It is common to start with an array of zeros and then fill in the entries using a loop. The `zeros` method can be used to create an array of zeros:

In [ ]:
np.zeros(3)

array([0., 0., 0.])

We can also create multi-dimensional arrays by using a tuple to specify the dimensions of the array.

In [ ]:
number_of_rows=3
number_of_columns=2
np.zeros((number_of_rows,number_of_columns))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

Defining an empty array like this can help with the efficiency of our programs, because doing so tells the computer how much memory it needs to allocate to this variable. However, we have to be careful that we don't overwrite entries with the wrong values.

There is a similar method that produces an array of ones:

In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

### More array creation functions

Beyond `np.zeros` and `np.ones`, NumPy provides several other useful creation functions.

**`np.full`** creates an array filled with a constant value:

In [ ]:
np.full((3, 4), fill_value=7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

**`np.eye`** creates an identity matrix — ones on the diagonal, zeros elsewhere. This appears frequently in linear algebra and machine learning:

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**`np.diag`** has two behaviours:
- Given a 2D array: extracts the diagonal elements.
- Given a 1D array: constructs a diagonal matrix.

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print("Diagonal of A:", np.diag(A))
print()
print("Diagonal matrix from [1,2,3]:")
print(np.diag([1, 2, 3]))

Diagonal of A: [1 5 9]

Diagonal matrix from [1,2,3]:
[[1 0 0]
 [0 2 0]
 [0 0 3]]


It is very common, particularly when plotting, to want an array of uniformly spaced numbers. The `linspace` method provides this:

In [ ]:
start=0
end=1
number_of_points=11
np.linspace(start,end,number_of_points)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Random number generation

NumPy provides a comprehensive set of functions for generating random numbers. Here we introduce the key functions and explain the differences between them.

| Function | Distribution | Range |
|---|---|---|
| `np.random.rand(d0, d1, ...)` | Uniform | [0, 1) |
| `np.random.randn(d0, d1, ...)` | Standard normal (mean=0, std=1) | (-∞, +∞) |
| `np.random.randint(low, high, size)` | Uniform integers | [low, high) |
| `np.random.normal(mean, std, size)` | Normal with specified mean and std | (-∞, +∞) |

In [ ]:
# Uniform random numbers in [0, 1)
print("rand (uniform):")
print(np.random.rand(2, 3))

# Standard normal: mean=0, std=1
print()
print("randn (standard normal):")
print(np.random.randn(2, 3))

# Random integers in [0, 10)
print()
print("randint:")
print(np.random.randint(0, 10, size=(2, 3)))

rand (uniform):
[[0.19190583 0.08268136 0.89523608]
 [0.97058795 0.82625793 0.96142809]]

randn (standard normal):
[[ 0.04257155  0.07248723 -0.2371074 ]
 [ 0.46059193 -0.16532601 -0.35972693]]

randint:
[[0 3 6]
 [7 4 4]]


### Reproducibility with `np.random.seed`

By default, NumPy's random functions produce different numbers each time. Setting a **random seed** fixes the sequence so you get the same output every time — essential for reproducible experiments and debugging:

In [ ]:
# Set a seed before any random calls
np.random.seed(42)
print("First call after seed=42:")
print(np.random.rand(3))

# Reset the same seed to reproduce identical results
np.random.seed(42)
print()
print("After resetting seed=42 (identical output):")
print(np.random.rand(3))

First call after seed=42:
[0.37454012 0.95071431 0.73199394]

After resetting seed=42 (identical output):
[0.37454012 0.95071431 0.73199394]


Setting `np.random.seed` at the top of a notebook is good practice whenever your code involves randomness and you need reproducible results.

## Operations on NumPy arrays

An important feature of NumPy arrays is that we can perform arithmetic on them. 

In [ ]:
# Define two arrays of the same size
x=np.array([0,1,2])
y=np.array([1,2,4])

In [ ]:
x+y

array([1, 3, 6])

In [ ]:
y-x

array([1, 1, 2])

In [ ]:
x/y

array([0. , 0.5, 0.5])

In [ ]:
y/x

<ipython-input-29-d2d3fa2acc3f>:1: RuntimeWarning: divide by zero encountered in true_divide
  y/x


array([inf,  2.,  2.])

Note that a warning was produced when we divided by zero. While this did not produce an error and NumPy used the data type `inf` to represent the result of dividing by zero, you should generally try to avoid dividing by zero in your code, as it will often result in errors, possibly in other parts of your code where it may not be easy to determine that the error resulted from the appearance of `inf`.  

NumPy also has another data type for mathematical calculations that are not defined:

In [ ]:
x/x

<ipython-input-30-5b73abf0f85e>:1: RuntimeWarning: invalid value encountered in true_divide
  x/x


array([nan,  1.,  1.])

Here `nan` that resulted from dividing 0/0, stands for "not a number". The appearance of a `nan` usually indicates a problem with the code that should be fixed. Calculations that involve `nan` and `inf` often result in one of those variables, so `nan` and `inf` tend to propagate, which can mean that calculations can return unexpected answers. Note however that `nan` can be used to represent missing data, as it is in the pandas package, although pandas includes various features to deal with missing data.

NumPy also has a range of standard mathematical functions and importantly these work element-wise (i.e. separately on each element) on NumPy arrays. This can be much faster than using a loop to compute the results of mathematical functions on many different values.

In [ ]:
np.sin(np.linspace(0,np.pi,10))

array([0.00000000e+00, 3.42020143e-01, 6.42787610e-01, 8.66025404e-01,
       9.84807753e-01, 9.84807753e-01, 8.66025404e-01, 6.42787610e-01,
       3.42020143e-01, 1.22464680e-16])

So far we have considered functions using arrays that are the same shape. However, NumPy can perform operations on arrays where the dimensions are either the same shape or one of them has dimension 1. This is called "broadcasting" and can be used to generalise scalar multiplication. For example, we would expect to be able to multiply an array by a constant:

In [ ]:
2*np.array([1,2])

array([2, 4])

### The broadcasting rule

Broadcasting allows NumPy to perform operations on arrays with different shapes. Rather than requiring arrays to be exactly the same size, NumPy follows a simple rule.

**The rule** — applied dimension by dimension, starting from the *trailing* (rightmost) dimension:

> Two dimensions are compatible if they are **equal**, or if **one of them is 1**.

A dimension of 1 is "stretched" to match the other array. No data is actually copied — NumPy handles this efficiently internally. If shapes have different numbers of dimensions, the shorter shape is padded with 1s on the left.

**Examples:**

In [ ]:
# Example 1: scalar broadcast over a 1D array
# () broadcast with (4,) → result (4,)
a = np.array([1, 2, 3, 4])
print("10 + [1,2,3,4] =", 10 + a)

# Example 2: 1D row broadcast over 2D matrix
# (3,) treated as (1,3) → broadcast with (2,3) → result (2,3)
row = np.array([1, 2, 3])
matrix = np.array([[10, 20, 30],
                   [40, 50, 60]])
print()
print("matrix + row (broadcast across each row):")
print(matrix + row)

10 + [1,2,3,4] = [11 12 13 14]

matrix + row (broadcast across each row):
[[11 22 33]
 [41 52 63]]


In [ ]:
# Example 3: column vector broadcast over 2D matrix
# (2,1) broadcast with (2,3) → result (2,3)
col = np.array([[100],
                [200]])   # shape (2, 1)
print("matrix + column vector (broadcast across each column):")
print(matrix + col)

matrix + column vector (broadcast across each column):
[[110 120 130]
 [240 250 260]]


In [ ]:
# Example 4: incompatible shapes → error
# (3,) cannot broadcast with (2,): 3 != 2 and neither is 1
try:
    np.array([1, 2, 3]) + np.array([10, 20])
except ValueError as e:
    print("Broadcasting error:", e)

Broadcasting error: operands could not be broadcast together with shapes (3,) (2,) 


**Shape compatibility summary:**

| Array A | Array B | Compatible? | Result |
|---|---|---|---|
| `(3,)` → `(1,3)` | `(2,3)` | Yes — 1 stretches to 2 | `(2,3)` |
| `(2,1)` | `(2,3)` | Yes — 1 stretches to 3 | `(2,3)` |
| `(3,)` → `(1,3)` | `(1,2)` | **No** — 3 ≠ 2 | Error |


This can be generalised to multi-dimensional arrays. For example, the following array

In [ ]:
x=np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
x

array([[[1, 1, 1],
        [2, 2, 2]],

       [[3, 3, 3],
        [4, 4, 4]]])

has shape

In [ ]:
x.shape

(2, 2, 3)

and consists of two-by-two matrices

In [ ]:
x[:,:,0]

array([[1, 2],
       [3, 4]])

stacked on top of each other in the third dimension of the array. Suppose we want to multiply each layer in the third dimension by a different amount, then we could make an array in that dimension with the corresponding multiplication factors. For example the array

In [ ]:
y=np.array([[[1,2,3]]])
y.shape

(1, 1, 3)

can be multiplied with the array x

In [ ]:
x*y

array([[[ 1,  2,  3],
        [ 2,  4,  6]],

       [[ 3,  6,  9],
        [ 4,  8, 12]]])

## Iterating

Arrays are iterable in the same way that lists are

In [ ]:
x=np.array([0,1,2])
for n in x:
    print(n)

0
1
2


There is also a NumPy version of `range` that allows non-integer step sizes

In [ ]:
start=0
stop=1
step=0.3
for i in np.arange(start,stop,step):
    print(i)

0.0
0.3
0.6
0.8999999999999999


Note how `arange` finished before the stop value. If you are iterating over non-integer values, it's good practice to check that the iterator goes through all of the intended values.

## Slicing

There is some additional functionality for slicing NumPy arrays over slicing lists. As an example, we'll use the following array.

In [ ]:
x=np.linspace(0,1,10)
x

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

Indexing and slicing operations from lists also work on arrays:

In [ ]:
x[0]

0.0

In [ ]:
x[:3]

array([0.        , 0.11111111, 0.22222222])

In [ ]:
x[-1]

1.0

In [ ]:
x[2:8]

array([0.22222222, 0.33333333, 0.44444444, 0.55555556, 0.66666667,
       0.77777778])

In [ ]:
x[2:8:2]

array([0.22222222, 0.44444444, 0.66666667])

An important difference is that entries can be assigned new values using slicing and indexing. For example

In [ ]:
x[2:8:2]=-1
x

array([ 0.        ,  0.11111111, -1.        ,  0.33333333, -1.        ,
        0.55555556, -1.        ,  0.77777778,  0.88888889,  1.        ])

### Slicing 2D arrays

All the slicing operations shown above apply to 1D arrays. For 2D arrays, you can slice along both dimensions simultaneously using the syntax `array[row_slice, column_slice]`.

In [ ]:
A = np.array([[10, 11, 12, 13],
              [20, 21, 22, 23],
              [30, 31, 32, 33],
              [40, 41, 42, 43]])
print(A)

[[10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


In [ ]:
# Single element: row 1, column 2 (zero-indexed)
print("A[1, 2] =", A[1, 2])

A[1, 2] = 22


In [ ]:
# Entire row (row 2)
print("Row 2:  ", A[2, :])
print("Row 2:  ", A[2])    # colon can be omitted for rows

Row 2:   [30 31 32 33]
Row 2:   [30 31 32 33]


In [ ]:
# Entire column (column 1)
print("Column 1:", A[:, 1])

Column 1: [11 21 31 41]


In [ ]:
# Sub-matrix: rows 1-2, columns 1-3
print("Sub-matrix A[1:3, 1:3]:")
print(A[1:3, 1:3])

Sub-matrix A[1:3, 1:3]:
[[21 22]
 [31 32]]


In [ ]:
# Every other row, every other column
print("Every other row and column A[::2, ::2]:")
print(A[::2, ::2])

Every other row and column A[::2, ::2]:
[[10 12]
 [30 32]]


Slicing can also be used to assign values to parts of a 2D array:

In [ ]:
B = A.copy()
B[0, :] = 0     # set entire first row to zero
B[:, -1] = -1   # set entire last column to -1
print(B)

[[ 0  0  0 -1]
 [20 21 22 -1]
 [30 31 32 -1]
 [40 41 42 -1]]


## Views vs copies

When you slice a NumPy array, the result is a **view** — it shares the same underlying data as the original. Modifying the view also modifies the original. This makes slicing fast and memory-efficient, but can cause surprising bugs if you are not aware of it.

In [ ]:
original = np.array([1, 2, 3, 4, 5])
view = original[1:4]     # view into elements at index 1, 2, 3

print("Before modification:")
print("original:", original)
print("view:    ", view)

view[0] = 99             # modifying the view...

print()
print("After modifying view[0] = 99:")
print("original:", original)  # ...also changes the original!
print("view:    ", view)

Before modification:
original: [1 2 3 4 5]
view:     [2 3 4]

After modifying view[0] = 99:
original: [ 1 99  3  4  5]
view:     [99  3  4]


To get an **independent copy** that does not affect the original, use `.copy()`:

In [ ]:
original = np.array([1, 2, 3, 4, 5])
copy = original[1:4].copy()

copy[0] = 99

print("After modifying copy[0] = 99:")
print("original:", original)  # unchanged
print("copy:    ", copy)

After modifying copy[0] = 99:
original: [1 2 3 4 5]
copy:     [99  3  4]


You can check whether two arrays share memory using `np.shares_memory()`:

In [ ]:
original = np.array([1, 2, 3, 4, 5])
view = original[1:4]
copy = original[1:4].copy()

print("view shares memory with original:", np.shares_memory(original, view))
print("copy shares memory with original:", np.shares_memory(original, copy))

view shares memory with original: True
copy shares memory with original: False


**Summary:**

| Operation | Returns | Modifying it affects original? |
|---|---|---|
| `a[1:4]` | View | **Yes** |
| `a[1:4].copy()` | Copy | No |
| `a.copy()` | Full copy | No |

**Rule of thumb:** if you want to modify a slice without affecting the original, always call `.copy()` first.

Furthermore, slicing operations can also be combined with logical operations. First let's create a matrix of random numbers

In [ ]:
x=np.random.rand(3,3)
x

array([[0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985]])

(Note that NumPy has built in functions for random number generation.)

We can apply logical operators to arrays. For example, the following determines which values of `x` are less than a half:

In [ ]:
x<0.5

array([[False,  True,  True],
       [ True, False, False],
       [False,  True, False]])

The output is an array of logical values and this can be used to index arrays of the same size. 

(If none of the values are less than a half, then you wish to re-run the cell above where `x` is assigned.)

For example, to get the values of the entries in `x` less than a half, we can do

In [ ]:
x[x<0.5]

array([0.15601864, 0.15599452, 0.05808361, 0.02058449])

We can then assign values to these.

In [ ]:
x[x<0.5]=0
x

array([[0.59865848, 0.        , 0.        ],
       [0.        , 0.86617615, 0.60111501],
       [0.70807258, 0.        , 0.96990985]])

We could also assign values using an array. In the example below, the values of `x` that are zero are replaced with normally distributed random numbers

In [ ]:
x[x==0]=np.random.randn(*x[x==0].shape)
# The * here unpacks a tuple into a function argument.
x

array([[ 0.59865848, -0.46947439,  0.54256004],
       [-0.46341769,  0.86617615,  0.60111501],
       [ 0.70807258, -0.46572975,  0.96990985]])

It is also possible to perform logical operations on arrays. For example, a logical "or" can be performed with the function `logical_or` or using the operator `|`:

In [ ]:
np.logical_or(x<0.1,x>0.9)

array([[False,  True, False],
       [ True, False, False],
       [False,  True,  True]])

In [ ]:
# The use of brackets is important here
(x<0.1) | (x>0.9)

array([[False,  True, False],
       [ True, False, False],
       [False,  True,  True]])

Similarly a logical "and" can be performed with the function `logical_and` or the operator `&`.

These can then used to slice and assign:

In [ ]:
x[(x<0.1) | (x>0.9)]=-10
x

array([[  0.59865848, -10.        ,   0.54256004],
       [-10.        ,   0.86617615,   0.60111501],
       [  0.70807258, -10.        , -10.        ]])

## `np.where`

`np.where` is the idiomatic NumPy way to apply conditional logic element-wise. With three arguments it selects values from two arrays based on a condition:

```python
np.where(condition, value_if_true, value_if_false)
```

In [ ]:
x = np.array([-3, -1, 0, 2, 4, -2, 5])

# Replace negative values with 0, keep positive values unchanged
result = np.where(x < 0, 0, x)
print("Original:        ", x)
print("Negatives → 0:   ", result)

Original:         [-3 -1  0  2  4 -2  5]
Negatives → 0:    [0 0 0 2 4 0 5]


In [ ]:
# Use different arrays for the two alternatives
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
condition = np.array([True, False, True, False, True])

print(np.where(condition, a, b))  # picks from a where True, b where False

[ 1 20  3 40  5]


In [ ]:
# Clip values to [0, 1] using np.where
data = np.array([0.1, 1.5, -0.3, 0.8, 2.1, -1.0])

clipped = np.where(data < 0, 0, np.where(data > 1, 1, data))
print("Original: ", data)
print("Clipped:  ", clipped)

# NumPy also has a dedicated clip method for this pattern:
print("np.clip:  ", np.clip(data, 0, 1))

Original:  [ 0.1  1.5 -0.3  0.8  2.1 -1. ]
Clipped:   [0.1 1.  0.  0.8 1.  0. ]
np.clip:   [0.1 1.  0.  0.8 1.  0. ]


**`np.where` with a single argument** returns the *indices* where the condition is true — useful for finding where something holds:

In [ ]:
x = np.array([5, 2, 8, 1, 9, 3])

indices = np.where(x > 4)
print("Indices where x > 4:", indices[0])
print("Values at those indices:", x[indices])

Indices where x > 4: [0 2 4]
Values at those indices: [5 8 9]


## Aggregation functions

NumPy provides a comprehensive set of functions to summarise arrays. These are much faster than Python's built-in equivalents on large arrays.

| Function | Description |
|---|---|
| `np.sum(a)` | Sum of all elements |
| `np.mean(a)` | Arithmetic mean |
| `np.min(a)` / `np.max(a)` | Minimum / maximum value |
| `np.std(a)` | Standard deviation |
| `np.var(a)` | Variance |
| `np.median(a)` | Median |
| `np.argmin(a)` / `np.argmax(a)` | Index of the minimum / maximum |
| `np.cumsum(a)` | Cumulative sum |

In [ ]:
data = np.array([4.0, 1.0, 7.0, 2.0, 9.0, 3.0])

print("Sum:   ", np.sum(data))
print("Mean:  ", np.mean(data))
print("Min:   ", np.min(data))
print("Max:   ", np.max(data))
print("Std:   ", np.std(data))
print("Median:", np.median(data))

Sum:    26.0
Mean:   4.333333333333333
Min:    1.0
Max:    9.0
Std:    2.8087165910587863
Median: 3.5


In [ ]:
# argmin / argmax return the INDEX of the extreme value
print("Index of minimum:", np.argmin(data), "  value:", data[np.argmin(data)])
print("Index of maximum:", np.argmax(data), "  value:", data[np.argmax(data)])

Index of minimum: 1   value: 1.0
Index of maximum: 4   value: 9.0


### The `axis` parameter

For 2D arrays, aggregation functions accept an `axis` argument:

- `axis=0` — collapse **rows**, producing one value per **column** (operates down)
- `axis=1` — collapse **columns**, producing one value per **row** (operates across)
- no `axis` — aggregate the **entire** array to a scalar

In [ ]:
M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(M)
print()
print("Total sum (no axis):          ", np.sum(M))
print("Column sums (axis=0):         ", np.sum(M, axis=0))
print("Row sums   (axis=1):          ", np.sum(M, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Total sum (no axis):           45
Column sums (axis=0):          [12 15 18]
Row sums   (axis=1):           [ 6 15 24]


In [ ]:
print("Column means (axis=0):         ", np.mean(M, axis=0))
print("Row maxima  (axis=1):         ", np.max(M, axis=1))
print("Column of row max (argmax):   ", np.argmax(M, axis=1))

Column means (axis=0):          [4. 5. 6.]
Row maxima  (axis=1):          [3 6 9]
Column of row max (argmax):    [2 2 2]


### Handling `nan` in aggregations

Real data often contains missing values represented as `np.nan`. Standard functions propagate `nan` — any operation involving `nan` returns `nan`. NumPy provides `nan`-safe alternatives:

In [ ]:
data_with_missing = np.array([1.0, 2.0, np.nan, 4.0, 5.0])

print("np.sum:     ", np.sum(data_with_missing))       # nan propagates
print("np.nansum:  ", np.nansum(data_with_missing))    # ignores nan

print("np.mean:    ", np.mean(data_with_missing))
print("np.nanmean: ", np.nanmean(data_with_missing))

print("np.nanmin:  ", np.nanmin(data_with_missing))
print("np.nanmax:  ", np.nanmax(data_with_missing))

np.sum:      nan
np.nansum:   12.0
np.mean:     nan
np.nanmean:  3.0
np.nanmin:   1.0
np.nanmax:   5.0


## Reshaping and flattening

It is often necessary to change the shape of an array without changing its data — for example, when preparing data for a machine learning model that expects a specific input shape.

### `reshape`

`.reshape()` returns a view of the array with a different shape. The total number of elements must stay the same.

In [ ]:
a = np.arange(12)
print("Original:", a, "  shape:", a.shape)
print()

# Reshape to 3 rows, 4 columns
B = a.reshape(3, 4)
print("reshape(3, 4):")
print(B)

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]   shape: (12,)

reshape(3, 4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# Use -1 to let NumPy infer one dimension automatically
C = a.reshape(4, -1)   # 4 rows; columns inferred as 12/4 = 3
print("reshape(4, -1)  →  shape:", C.shape)
print(C)

reshape(4, -1)  →  shape: (4, 3)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
# Reshape to 3D
D = a.reshape(2, 3, 2)
print("reshape(2, 3, 2)  →  shape:", D.shape)
print(D)

reshape(2, 3, 2)  →  shape: (2, 3, 2)
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


### Flattening: `ravel` and `flatten`

Both `ravel()` and `flatten()` collapse a multi-dimensional array into 1D. The key difference:

| Method | Returns | Modifying result affects original? |
|---|---|---|
| `.ravel()` | View (where possible) | **Yes** |
| `.flatten()` | Always a copy | No |

In [ ]:
M = np.array([[1, 2, 3],
              [4, 5, 6]])

print("ravel():  ", M.ravel())
print("flatten():", M.flatten())

# Demonstrate view vs copy behaviour
r = M.ravel()
r[0] = 99
print()
print("After modifying ravel result, M =")
print(M)   # M changed because ravel returned a view

f = M.flatten()
f[0] = 0
print()
print("After modifying flatten result, M =")
print(M)   # M unchanged because flatten returned a copy

ravel():   [1 2 3 4 5 6]
flatten(): [1 2 3 4 5 6]

After modifying ravel result, M =
[[99  2  3]
 [ 4  5  6]]

After modifying flatten result, M =
[[99  2  3]
 [ 4  5  6]]


Use `ravel()` for efficient computation when you do not need an independent copy. Use `flatten()` when you need a 1D copy you can safely modify without affecting the original array.

## Stacking and concatenation

It is common to combine multiple arrays into one — for example, when assembling a feature matrix or merging batches of data.

### `np.concatenate`

Joins arrays along an **existing** axis:

In [ ]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

# axis=0: add rows (stack vertically)
print("concatenate axis=0:")
print(np.concatenate([a, b], axis=0))
print()

# axis=1: add columns (stack horizontally)
print("concatenate axis=1:")
print(np.concatenate([a, b], axis=1))

concatenate axis=0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

concatenate axis=1:
[[1 2 5 6]
 [3 4 7 8]]


### `np.vstack` and `np.hstack`

Convenient shortcuts for vertical and horizontal stacking:

In [ ]:
print("vstack (same as concatenate axis=0):")
print(np.vstack([a, b]))
print()

print("hstack (same as concatenate axis=1):")
print(np.hstack([a, b]))

vstack (same as concatenate axis=0):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

hstack (same as concatenate axis=1):
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# hstack on 1D arrays simply concatenates them
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print("hstack of 1D arrays:", np.hstack([x, y]))

**Quick reference:**

| Function | What it does | Adds a new axis? |
|---|---|---|
| `np.concatenate([a,b], axis=k)` | Join along existing axis k | No |
| `np.vstack([a,b])` | Stack vertically (axis=0) | No |
| `np.hstack([a,b])` | Stack horizontally (axis=1 for 2D) | No |


## Vectorisation

NumPy arrays are intended to represent vectors and matrices, and so naturally we might want to perform vector and matrix multiplication (rather than element-wise multiplication). Consider the following vector and matrix:

In [ ]:
x=np.array([1,2,3])
y=np.array([[1,2],[3,4],[5,6]])

The `@` operator can be used to compute the vector product

In [ ]:
x @ y

array([22, 28])

and there is also a corresponding method

In [ ]:
np.matmul(x,y)

array([22, 28])

Note that NumPy will raise an error if the size of the arrays you wish to multiply do not work:

In [ ]:
y @ x

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

Vectorisation is the process of computing on arrays rather than using for loops. For example, it sometimes possible to replace a loop with vector/matrix multiplication, and this may be faster. To demonstrate this, suppose we want to compute the sum of 10,000 uniformly distributed random variables, and we want to do this 100 times. First lets draw all of the random numbers:

In [ ]:
n=10000
m=100
x=np.random.rand(m,n)

We could use a list comprehension to loop over the rows of the matrix and sum them up:

In [ ]:
%%timeit
[x[i,:].sum() for i in range(m)]

1.28 ms ± 121 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In this case, summing up is equivalent to multiplying on the right by a column vector of ones, and doing this is faster:

In [ ]:
%%timeit
x @ np.ones(n)

223 µs ± 6.58 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


However, there would be a smaller difference in speed if the number of rows (`m`) was smaller. Vectorising code can also use more computer memory, which could slow down the computations.

It's also usually quicker to perform operations on arrays rather than using loops. For example, below we compare summing up a million uniformly distributed random variables.

In [ ]:
n=1000000

Using the NumPy sum function:

In [ ]:
%%time
np.sum(np.random.rand(n))

Wall time: 10.8 ms


499478.4609301184

Using a list comprehension and the built in function `sum`:

In [ ]:
%%time
sum([np.random.rand() for i in range(n)])

Wall time: 411 ms


500118.3801513582

Using a loop:

In [ ]:
%%time
tot=0
for i in range(n):
    tot+=np.random.rand()
print(tot)

500100.5875597657
Wall time: 408 ms


It can also be much better to create vectorised functions, i.e. functions that can work take arrays as arguments (and ideally scalars as well). The following function works element-wise on both arrays and numerical values:

In [ ]:
def linear_combination(a,x,t):
    return x*np.exp(-a*t)

It also runs much quicker on arrays than using list comprehensions:

In [ ]:
# Set up the function arguments
a=2
n=1000
t=np.linspace(0,10,n)
x=np.random.rand(n)

In [ ]:
%%timeit
# Computing on arrays
y=linear_combination(a,x,t)

8.08 µs ± 493 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
%%timeit
# Computing using a list comprehension
y=[linear_combination(a,x[i],t[i]) for i in range(n)]

1.56 ms ± 66.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Hopefully you should see that using arrays is much faster (it was about 140 times faster on the computer on which this notebook was written).

It may not be possible to write a function that can work with both arrays and numerical values, but if you know you will want to apply a function to arrays, then it's is generally much faster than looping. The following example function computes the square root of only positive values of an array.

In [ ]:
def root_positive_numbers_vectorised(x):
    y=x.copy() # This ensures that the values in x are not over written
    y[x>0]=np.sqrt(y[x>0])
    return y

To illustrate what this function does:

In [ ]:
x=np.linspace(-3,3,7)
x

array([-3., -2., -1.,  0.,  1.,  2.,  3.])

In [ ]:
y=root_positive_numbers_vectorised(x)

In [ ]:
y

array([-3.        , -2.        , -1.        ,  0.        ,  1.        ,
        1.41421356,  1.73205081])

An equivalent function that only worked on numerical values would be:

In [ ]:
def root_positive_numbers(x):
    if x>0:
        return np.sqrt(x)
    else:
        return x

Now we will compare the vectorised and non-vectorised functions on some random numbers

In [38]:
n=1000000
# Create normally distributed random variables
x=np.random.randn(n)

In [ ]:
%%timeit 
y=root_positive_numbers_vectorised(x)

15.3 ms ± 345 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
%%timeit 
y=[root_positive_numbers(z) for z in x]

789 ms ± 11.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
%%timeit 
y=list(map(root_positive_numbers,x))

801 ms ± 41.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Hopefully you will again see that the vectorised approach is much faster (it was about 40 times faster on the computer on which this notebook was written).