# Unit 4 – Practice & Consolidation Worksheet

These exercises are for your own practice and are **not graded**. Work through them after completing the Unit 4 reading material. Attempt each exercise before revealing the answer.

## Exercise types

| Type | What to do |
|---|---|
| Predict the output | Write what you think the code will print *before* running the cell |
| Fix the bug | The code contains an error — find and correct it |
| Fill in the blank | Complete the missing line(s) to produce the expected output |
| Adapt and extend | A working example is given — modify it to solve a related problem |

**Topics:** array creation and attributes · indexing and slicing · boolean indexing and `np.where` · aggregations and the axis parameter · reshaping and stacking · Matplotlib — plot types and customisation · subplots

---

## Section 1 – Array Creation and Attributes

### Exercise 1.1 Predict the output

Without running the cell, write down what each `print` statement will output.

```python
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a.shape)
print(a.size)
print(a.ndim)
print(a.dtype)
```

<details>
<summary><strong>Select here for answer</strong></summary>

```python
# (2, 3)
# 6
# 2
# int64  (or int32 on Windows)
```

`shape` returns a tuple of dimensions — 2 rows, 3 columns. `size` is the total number of elements: 2 × 3 = 6. `ndim` is the number of axes (2 for a matrix). `dtype` is inferred from the values — all integers give `int64` on most platforms.

</details>

### Exercise 1.2 Fill in the blank

Complete the code to create the arrays described in the comments.

```python
import numpy as np

# A 4×3 array of zeros
zeros = np.________(________)

# 7 evenly spaced values from 0 to 1 inclusive
line = np.________(0, 1, ________)

# A 3×3 identity matrix
eye = np.________(3)

print(zeros.shape)
print(line)
print(eye)
```

<details>
<summary><strong>Select here for answer</strong></summary>

```python
zeros = np.zeros((4, 3))
line  = np.linspace(0, 1, 7)
eye   = np.eye(3)
```

`np.zeros` takes a shape tuple — note the double parentheses: the outer ones call the function, the inner ones form the tuple. `np.linspace(start, stop, n)` includes both endpoints and produces exactly `n` values. `np.eye(n)` creates an `n×n` identity matrix.

</details>

### Exercise 1.3 Fix the bug

The code is meant to create a reproducible random array and print its shape, but it raises an error. Fix it.

```python
import numpy as np

np.random.seed = 42
data = np.random.randn(3, 4)
print(data.shape)
```

<details>
<summary><strong>Select here for answer</strong></summary>

```python
np.random.seed(42)
data = np.random.randn(3, 4)
print(data.shape)
```

`np.random.seed` is a **function**, not an attribute — it must be called with parentheses: `np.random.seed(42)`. Writing `np.random.seed = 42` silently replaces the function with the integer 42, which then causes a `TypeError` on the next line.

</details>

### Exercise 1.4 Predict the output

What will this code print? Think carefully about how `dtype` affects the result.

```python
import numpy as np

a = np.array([1.0, 2.5, 3.7], dtype=np.int32)
print(a)
print(a.dtype)
```

<details>
<summary><strong>Select here for answer</strong></summary>

```python
# [1 2 3]
# int32
```

When casting floats to `int32`, NumPy **truncates** (drops the decimal part) rather than rounding. So `2.5` becomes `2` and `3.7` becomes `3`. This is a common source of silent data loss when converting arrays between types.

</details>

### Exercise 1.5 Adapt and extend

The example below creates a 1D array using `np.arange`:

```python
import numpy as np
x = np.arange(0, 10, 2)   # [0, 2, 4, 6, 8]
print(x)
```

Adapt it to create a 2D array `M` with shape `(3, 4)` containing the integers 0–11 in row-major order (i.e. `[[0,1,2,3],[4,5,6,7],[8,9,10,11]]`). Then confirm its shape and print the value of the element in row 2, column 3.

```python
import numpy as np

# Your code here
```

<details>
<summary><strong>Select here for answer</strong></summary>

```python
M = np.arange(12).reshape(3, 4)
print(M.shape)   # (3, 4)
print(M[2, 3])   # 11
```

`np.arange(12)` produces `[0, 1, ..., 11]`. Chaining `.reshape(3, 4)` reshapes it into 3 rows of 4 without copying the data. `M[2, 3]` uses zero-based indexing: row index 2 is the third row, column index 3 is the fourth column.

</details>

---
## Section 2 – Indexing and Slicing

### Exercise 2.1 Predict the output

What does each slice extract from the matrix `A`?

```python
import numpy as np

A = np.array([[10, 11, 12, 13],
              [20, 21, 22, 23],
              [30, 31, 32, 33],
              [40, 41, 42, 43]])

print(A[1, :])
print(A[:, 2])
print(A[1:3, 1:3])
print(A[::2, ::2])
```

<details>
<summary><strong>Select here for answer</strong></summary>

```python
# [20 21 22 23]        — entire row 1
# [12 22 32 42]        — entire column 2
# [[21 22]             — sub-matrix rows 1-2, cols 1-2
#  [31 32]]
# [[10 12]             — every other row and column
#  [30 32]]
```

Row slicing uses the first index, column slicing uses the second after the comma. `A[1:3, 1:3]` selects rows with indices 1 and 2 (stop is exclusive) and columns 1 and 2. The `::2` step syntax selects every other element starting from index 0.

</details>

### Exercise 2.2 Fix the bug

The code is meant to set every element in the last column of `B` to zero, but it modifies the wrong slice. Fix it.

```python
import numpy as np

B = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B[-1, :] = 0   # intended: last column → 0
print(B)
```

Expected output:
```
[[1 2 0]
 [4 5 0]
 [7 8 0]]
```

<details>
<summary><strong>Select here for answer</strong></summary>

```python
B[:, -1] = 0
```

`B[-1, :]` selects the **last row** (index −1) across all columns. To select the **last column** across all rows, use `B[:, -1]`. The first index position is always rows, the second is always columns.

</details>

### Exercise 2.3 Predict the output

Views and copies behave differently. What will be printed after each modification?

```python
import numpy as np

original = np.array([10, 20, 30, 40, 50])
view = original[1:4]
copy = original[1:4].copy()

view[0] = 99
copy[2] = 77

print(original)
```

<details>
<summary><strong>Select here for answer</strong></summary>

```python
# [10 99 30 40 50]
```

Modifying `view[0]` changes `original[1]` because a slice returns a **view** — it shares memory with the original. Modifying `copy[2]` does not affect `original` because `.copy()` creates an independent array. Only the view modification is visible in `original`.

</details>

### Exercise 2.4 Fill in the blank

Complete the code to extract the sub-matrix highlighted below from `M`, then replace all values in the top-right 2×2 block with −1.

`M` is:
```
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
```

Expected `sub` (rows 0–1, columns 2–3):
```
[[ 2  3]
 [ 6  7]]
```

```python
import numpy as np

M = np.arange(12).reshape(3, 4)
sub = M[________, ________]
print(sub)

M[________, ________] = -1
print(M)
```

<details>
<summary><strong>Select here for answer</strong></summary>

```python
sub = M[0:2, 2:4]
print(sub)

M[0:2, 2:4] = -1
print(M)
```

`0:2` selects row indices 0 and 1 (stop exclusive). `2:4` selects column indices 2 and 3. Because `sub` is a view into `M`, modifying `M[0:2, 2:4]` after extracting `sub` would also change `sub` — but here we print `sub` first so this does not affect the output.

</details>

### Exercise 2.5 Adapt and extend

The example below selects every other element from a 1D array:

```python
import numpy as np
x = np.arange(10)
print(x[::2])   # [0 2 4 6 8]
```

Adapt it to work with a 2D array. Given the matrix below, create `result` by selecting every other row **and** reversing the column order (i.e. columns from right to left).

```python
import numpy as np

G = np.array([[1,  2,  3,  4],
              [5,  6,  7,  8],
              [9,  10, 11, 12],
              [13, 14, 15, 16]])

# Your code here — expected result:
# [[ 4  3  2  1]
#  [12 11 10  9]]
```

<details>
<summary><strong>Select here for answer</strong></summary>

```python
result = G[::2, ::-1]
print(result)
```

`::2` in the row position selects rows 0 and 2 (every other row starting from 0). `::-1` in the column position reverses the column order. Both step values can be combined in a single slice — no loop needed.

</details>

---
## Section 3 – Boolean Indexing and `np.where`

### Exercise 3.1 Predict the output

What will each `print` statement output?

```python
import numpy as np

temps = np.array([18.2, 24.5, 31.0, 15.8, 27.3, 22.1, 35.6])

print(temps > 25)
print(temps[temps > 25])
print((temps > 25).sum())
```

<details>
<summary><strong>Select here for answer</strong></summary>

```python
# [False  False  True False  True False  True]
# [31.  27.3 35.6]
# 3
```

The boolean mask has `True` wherever `temps > 25`. `24.5` is not greater than 25, so it is excluded. The filtered array contains only the three values above 25. `.sum()` counts the `True` values because `True == 1` in NumPy.

</details>

### Exercise 3.2 Fill in the blank

Use boolean indexing to replace all negative values in `signal` with `0`, then use `np.where` to create `clipped` — values below −1 become −1, values above 1 become 1, others stay unchanged.

```python
import numpy as np

signal = np.array([0.5, -0.3, 1.2, -1.8, 0.9, -0.1, 2.1])

# Replace negatives with 0 using boolean indexing
signal[________] = 0
print(signal)

# Clip to [-1, 1] using np.where (restore original for this step)
signal = np.array([0.5, -0.3, 1.2, -1.8, 0.9, -0.1, 2.1])
clipped = np.where(________, -1, np.where(________, 1, signal))
print(clipped)
```

<details>
<summary><strong>Select here for answer</strong></summary>

```python
signal[signal < 0] = 0
print(signal)
# [0.5 0.  1.2 0.  0.9 0.  2.1]

signal = np.array([0.5, -0.3, 1.2, -1.8, 0.9, -0.1, 2.1])
clipped = np.where(signal < -1, -1, np.where(signal > 1, 1, signal))
print(clipped)
# [ 0.5 -0.3  1.  -1.   0.9 -0.1  1. ]
```

Boolean indexing on the left-hand side of an assignment sets matching elements in place. Nested `np.where` applies two conditions in sequence — the outer handles the lower bound, the inner handles the upper bound. NumPy also provides `np.clip(signal, -1, 1)` as a cleaner one-liner for this specific pattern.

</details>

### Exercise 3.3 Fix the bug

The code tries to find elements that are either below 5 or above 15, but raises a `ValueError`. Fix it.

```python
import numpy as np

data = np.array([3, 8, 12, 2, 17, 6, 19])
result = data[data < 5 or data > 15]
print(result)
```

<details>
<summary><strong>Select here for answer</strong></summary>

```python
result = data[(data < 5) | (data > 15)]
print(result)  # [ 3  2 17 19]
```

Python's `or` keyword operates on single boolean values and cannot be applied element-wise to arrays — NumPy raises a `ValueError` because the truth value of an array is ambiguous. Use the bitwise operator `|` for element-wise OR. Each condition must also be wrapped in parentheses because `|` has lower precedence than `<` and `>`.

</details>

### Exercise 3.4 Predict the output

Trace through this `np.where` call and predict the output.

```python
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

result = np.where(a % 2 == 0, b, a)
print(result)
```

<details>
<summary><strong>Select here for answer</strong></summary>

```python
# [ 1 20  3 40  5]
```

`a % 2 == 0` is `[False, True, False, True, False]`. True wherever the value in `a` is even. The even values are 2 and 4, at positions 1 and 3, so `np.where` takes the corresponding entries from b (20 and 40). At the remaining positions (the odd values 1, 3 and 5) it takes the entries from `a. np.where(condition, true_array, false_array)` selects element-wise.

</details>

### Exercise 3.5 Adapt and extend

The example below uses `np.where` to label values as `'high'` or `'low'`:

```python
import numpy as np
scores = np.array([45, 72, 88, 61, 93])
labels = np.where(scores >= 70, 'high', 'low')
print(labels)  # ['low' 'high' 'high' 'low' 'high']
```

Adapt it to produce a three-category label array: `'low'` (below 60), `'medium'` (60–79), `'high'` (80 and above). Use nested `np.where`.

```python
import numpy as np
scores = np.array([45, 72, 88, 61, 93, 55, 76])

# Your code here
# Expected: ['low' 'medium' 'high' 'medium' 'high' 'low' 'medium']
```

<details>
<summary><strong>Select here for answer</strong></summary>

```python
labels = np.where(scores < 60, 'low', np.where(scores < 80, 'medium', 'high'))
print(labels)
```

The outer `np.where` handles the lowest category. The inner `np.where` (the `false` branch of the outer) handles the remaining two. The innermost condition `scores < 80` separates medium from high. This pattern mirrors an `if/elif/else` chain applied element-wise across the whole array.

</details>

---
## Section 4 – Aggregations and the Axis Parameter

### Exercise 4.1 Predict the output

What will each aggregation print? Pay close attention to the `axis` argument.

```python
import numpy as np

M = np.array([[3, 1, 4],
              [1, 5, 9],
              [2, 6, 5]])

print(np.sum(M))
print(np.sum(M, axis=0))
print(np.sum(M, axis=1))
print(np.argmax(M, axis=1))
```

<details>
<summary><strong>Select here for answer</strong></summary>

```python
# 36
# [6 12 18]         — column sums
# [8 15 13]          — row sums
# [2 2 1]            — column index of max in each row
```

`np.sum(M)` with no axis sums all 9 elements. `axis=0` collapses rows (operates down each column): 3+1+2=6, 1+5+6=12, 4+9+5=18. `axis=1` collapses columns (operates across each row): 3+1+4=8, etc. `argmax(axis=1)` returns the column index of the largest value in each row.

</details>

### Exercise 4.2 Fill in the blank

A dataset of daily rainfall (mm) has some missing values recorded as `np.nan`. Complete the code to compute the mean rainfall, ignoring missing values, then find the index of the wettest day.

```python
import numpy as np

rainfall = np.array([2.1, np.nan, 5.4, 0.0, np.nan, 8.3, 1.2])

mean_rain = np.________(rainfall)
print(f"Mean: {mean_rain:.2f} mm")

wettest_idx = np.________(rainfall)
print(f"Wettest day index: {wettest_idx}")
```

<details>
<summary><strong>Select here for answer</strong></summary>

```python
mean_rain = np.nanmean(rainfall)
print(f'Mean: {mean_rain:.2f} mm')

wettest_idx = np.nanargmax(rainfall)
print(f'Wettest day index: {wettest_idx}')
```

`np.nanmean` ignores `nan` values when computing the mean — `np.mean` would return `nan` if any element is `nan`. Similarly, `np.nanargmax` finds the index of the maximum while skipping `nan`. Always use the `nan`-safe variants when your data may have missing values.

</details>

### Exercise 4.3 Fix the bug

The code is meant to normalise each **row** of `M` so that the values in each row sum to 1, but it produces the wrong result. Fix it.

```python
import numpy as np

M = np.array([[1.0, 3.0, 6.0],
              [2.0, 2.0, 6.0]])

row_sums = M.sum(axis=1)
M_normalised = M / row_sums
print(M_normalised)
```

<details>
<summary><strong>Select here for answer</strong></summary>

```python
row_sums = M.sum(axis=1)
M_normalised = M / row_sums[:, np.newaxis]   # or row_sums.reshape(-1, 1)
print(M_normalised)
```

`row_sums` has shape `(2,)` — a 1D array with one value per row. Dividing `M` (shape `(2, 3)`) by `row_sums` (shape `(2,)`) broadcasts incorrectly: NumPy aligns dimensions from the right, so it tries to divide each column by each row sum. Adding `[:, np.newaxis]` reshapes `row_sums` to `(2, 1)`, which then broadcasts correctly across each row.

</details>

### Exercise 4.4 Predict the output

```python
import numpy as np

data = np.array([4.0, 1.0, 7.0, 2.0, 9.0, 3.0])

print(np.min(data))
print(np.argmin(data))
print(np.median(data))
print(np.std(data))
```

<details>
<summary><strong>Select here for answer</strong></summary>

```python
# 1.0
# 1       — index of the minimum
# 3.5     — median of [1, 2, 3, 4, 7, 9]
# 2.8...  — standard deviation (approx 2.81)
```

`np.argmin` returns the **index** of the smallest value, not the value itself, useful for locating where the minimum occurs. `np.median` sorts the values and returns the middle one (or the mean of the two middle values for an even-length array): sorted data is `[1, 2, 3, 4, 7, 9]`, so the median is `(3 + 4) / 2 = 3.5`.

</details>

### Exercise 4.5 Adapt and extend

The example below computes column means of a matrix:

```python
import numpy as np
M = np.random.randint(0, 10, size=(4, 5))
col_means = np.mean(M, axis=0)
print(col_means)
```

Adapt it to:
1. Generate a `(6, 4)` random integer matrix with values 0–100 using `np.random.seed(7)`.
2. Compute the **row** standard deviation.
3. Find the **index** of the row with the highest standard deviation (i.e. most variable row).

```python
import numpy as np

# Your code here
```

<details>
<summary><strong>Select here for answer</strong></summary>

```python
np.random.seed(7)
M = np.random.randint(0, 101, size=(6, 4))
row_std = np.std(M, axis=1)
most_variable = np.argmax(row_std)
print('Row std devs:', row_std)
print('Most variable row index:', most_variable)
```

`axis=1` operates across columns within each row, producing one standard deviation per row. `np.argmax` then finds which row has the largest std. Combining `std` and `argmax` is a common pattern for identifying the most or least consistent observation in a dataset.

</details>

---
## Section 5 – Reshaping and Stacking

### Exercise 5.1 Predict the output

```python
import numpy as np

a = np.arange(24)
B = a.reshape(4, 6)
C = a.reshape(2, 3, -1)

print(B.shape)
print(C.shape)
print(C[1, 2, 3])
```

<details>
<summary><strong>Select here for answer</strong></summary>

```python
# (4, 6)
# (2, 3, 4)
# 23
```

In `reshape(2, 3, -1)`, the `-1` tells NumPy to infer the last dimension: 24 / (2 × 3) = 4. `C[1, 2, 3]` accesses the element at block 1, row 2, column 3. In row-major order, this corresponds to index 1×12 + 2×4 + 3 = 23.

</details>

### Exercise 5.2 Fill in the blank

Complete the code to stack the two arrays vertically, then horizontally, then flatten the result.

```python
import numpy as np

x = np.array([[1, 2, 3],
              [4, 5, 6]])

y = np.array([[7, 8, 9],
              [10, 11, 12]])

vertical   = np.________(x, y)     # 4 rows, 3 cols
horizontal = np.________(x, y)     # 2 rows, 6 cols
flat       = vertical.________()   # 1D, 12 elements

print(vertical.shape)
print(horizontal.shape)
print(flat)
```

<details>
<summary><strong>Select here for answer</strong></summary>

```python
vertical   = np.vstack([x, y])
horizontal = np.hstack([x, y])
flat       = vertical.flatten()
```

`np.vstack` stacks along axis 0 (adds rows); `np.hstack` stacks along axis 1 (adds columns). Both are convenience wrappers around `np.concatenate` with the appropriate `axis` argument. `.flatten()` always returns a copy; `.ravel()` returns a view when possible and is slightly faster.

</details>

### Exercise 5.3 Fix the bug

The code is meant to reshape `data` into a 3×4 matrix, but raises a `ValueError`. Fix it.

```python
import numpy as np

data = np.arange(10)
M = data.reshape(3, 4)
print(M)
```

<details>
<summary><strong>Select here for answer</strong></summary>

```python
data = np.arange(12)
M = data.reshape(3, 4)
```

A `(3, 4)` matrix requires 3 × 4 = 12 elements, but `np.arange(10)` only produces 10. NumPy raises a `ValueError` because the total number of elements cannot change during a reshape. Either change the source array (`np.arange(12)`) or the target shape (`reshape(2, 5)`).

</details>

### Exercise 5.4 Predict the output

```python
import numpy as np

M = np.array([[1, 2, 3],
              [4, 5, 6]])

r = M.ravel()
r[0] = 99

f = M.flatten()
f[0] = 77

print(M)
```

<details>
<summary><strong>Select here for answer</strong></summary>

```python
# [[99  2  3]
#  [ 4  5  6]]
```

`ravel()` returns a **view** when the array is contiguous in memory — modifying `r[0]` changes `M[0, 0]`. `flatten()` always returns an independent **copy** — modifying `f[0]` has no effect on `M`. So only the `ravel` modification is visible.

</details>

### Exercise 5.5 Adapt and extend

The example below concatenates two 1D arrays:

```python
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.concatenate([a, b]))  # [1 2 3 4 5 6]
```

Adapt it to:
1. Create three `(2, 3)` matrices filled with 1s, 2s, and 3s respectively (use `np.full`).
2. Concatenate them along axis 0 (stack rows) into a `(6, 3)` result.
3. Concatenate them along axis 1 (stack columns) into a `(2, 9)` result.
4. Print both shapes to confirm.

```python
import numpy as np

# Your code here
```

<details>
<summary><strong>Select here for answer</strong></summary>

```python
A = np.full((2, 3), 1)
B = np.full((2, 3), 2)
C = np.full((2, 3), 3)

row_stack = np.concatenate([A, B, C], axis=0)
col_stack = np.concatenate([A, B, C], axis=1)

print(row_stack.shape)  # (6, 3)
print(col_stack.shape)  # (2, 9)
```

`np.full((2, 3), fill_value)` creates an array of the given shape filled with a constant. `axis=0` stacks along the row axis (adds rows); `axis=1` stacks along the column axis (adds columns). `np.vstack` and `np.hstack` are equivalent shorthands for these two cases.

</details>

---
## Section 6 – Matplotlib: Plot Types and Customisation

### Exercise 6.1 Fix the bug

The code is meant to produce a line plot with a title, axis labels, and a legend, but it raises an `AttributeError`. Fix it.

```python
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 2 * np.pi, 100)
y = np.sin(x)

fig, ax = plt.subplots()
plt.plot(x, y, label='sin(x)', color='#12355C', linewidth=2)
plt.set_title('Sine wave')
plt.set_xlabel('x')
plt.set_ylabel('Amplitude')
plt.legend()
plt.show()
```

<details>
<summary><strong>Select here for answer</strong></summary>

```python
fig, ax = plt.subplots()
ax.plot(x, y, label='sin(x)', color='#12355C', linewidth=2)
ax.set_title('Sine wave')
ax.set_xlabel('x')
ax.set_ylabel('Amplitude')
ax.legend()
plt.show()
```

`plt.set_title`, `plt.set_xlabel`, and `plt.set_ylabel` do not exist — `set_title`, `set_xlabel`, and `set_ylabel` are **methods on the `Axes` object** (`ax`). `plt.plot` does work (state-based style), but mixing `plt.plot` with `ax.set_*` methods is inconsistent. Use either fully object-oriented (`ax.*`) or fully state-based (`plt.*`) — the object-oriented style is preferred.

</details>

### Exercise 6.2 Fill in the blank

Complete the code to create a figure with two side-by-side plots:
- Left: a scatter plot of `x` vs `y` with marker size proportional to `sizes`
- Right: a bar chart of `categories` vs `values`

```python
import matplotlib.pyplot as plt
import numpy as np

x = [1, 2, 3, 4, 5]
y = [3, 7, 2, 9, 5]
sizes = [50, 200, 80, 300, 120]

categories = ['A', 'B', 'C', 'D']
values = [15, 9, 22, 11]

fig, axs = plt.subplots(1, 2, figsize=(10, 4))

axs[0].________(x, y, s=sizes, color='#12355C', alpha=0.7)
axs[0].set_title('Scatter plot')
axs[0].set_xlabel('x')

axs[1].________(categories, values, color='#D86175')
axs[1].set_title('Bar chart')
axs[1].set_ylabel('Value')

plt.tight_layout()
plt.show()
```

<details>
<summary><strong>Select here for answer</strong></summary>

```python
axs[0].scatter(x, y, s=sizes, color='#12355C', alpha=0.7)
axs[1].bar(categories, values, color='#D86175')
```

`scatter` takes `s` (size in points²) as a keyword argument — passing a list makes each marker a different size. `bar` takes positional arguments for the x positions (or category labels) and heights. `plt.tight_layout()` automatically adjusts subplot spacing to prevent labels overlapping.

</details>

### Exercise 6.3 Predict the output

Before running the code, describe what the plot will look like — how many subplots, what type, and what data each shows.

```python
import matplotlib.pyplot as plt
import numpy as np

np.random.seed(0)
data1 = np.random.normal(loc=60, scale=10, size=500)
data2 = np.random.normal(loc=75, scale=8, size=500)

fig, axs = plt.subplots(1, 2, figsize=(12, 4))

axs[0].hist(data1, bins=25, color='#12355C', alpha=0.7, label='Group 1')
axs[0].hist(data2, bins=25, color='#D86175', alpha=0.7, label='Group 2')
axs[0].set_title('Overlapping histograms')
axs[0].legend()

axs[1].boxplot([data1, data2], labels=['Group 1', 'Group 2'])
axs[1].set_title('Box plots')

plt.tight_layout()
plt.show()
```

<details>
<summary><strong>Select here for answer</strong></summary>

```python
# Two side-by-side plots:
# Left: overlapping histograms of two normal distributions,
#        Group 1 centred around 60 (std 10), Group 2 around 75 (std 8)
# Right: side-by-side box plots of the same two groups
```

The `alpha=0.7` makes both histograms semi-transparent so they can overlap without one fully hiding the other. The box plots show median, IQR, whiskers, and outliers for each group. Group 2 will appear shifted to the right with a slightly narrower spread than Group 1.

</details>

### Exercise 6.4 Fix the bug

The code is meant to add a legend to a line plot, but no legend appears. Fix it.

```python
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 10, 100)

fig, ax = plt.subplots()
ax.plot(x, np.sin(x), color='#12355C', linewidth=2)
ax.plot(x, np.cos(x), color='#D86175', linewidth=2)
ax.legend()
plt.show()
```

<details>
<summary><strong>Select here for answer</strong></summary>

```python
ax.plot(x, np.sin(x), color='#12355C', linewidth=2, label='sin(x)')
ax.plot(x, np.cos(x), color='#D86175', linewidth=2, label='cos(x)')
ax.legend()
```

`ax.legend()` only displays entries for lines that have a `label` argument set when they are plotted. Without `label=`, the lines exist in the figure but have no legend entries — calling `legend()` produces an empty legend box. Add `label='sin(x)'` and `label='cos(x)'` to the two `plot` calls.

</details>

### Exercise 6.5 Adapt and extend

The example below plots a single sine curve:

```python
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 2 * np.pi, 200)
fig, ax = plt.subplots()
ax.plot(x, np.sin(x))
plt.show()
```

Adapt it to create a `(2, 2)` grid of subplots with `sharex=True`. Plot sin, cos, sin², and cos² in the four panels. Give each a title, label the x axis on the bottom row only (this is handled by `sharex=True`), and add a y-axis label to each panel.

```python
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 2 * np.pi, 200)

# Your code here
```

<details>
<summary><strong>Select here for answer</strong></summary>

```python
fig, axs = plt.subplots(2, 2, figsize=(10, 7), sharex=True)

axs[0, 0].plot(x, np.sin(x), color='#12355C')
axs[0, 0].set_title('sin(x)')
axs[0, 0].set_ylabel('Amplitude')

axs[0, 1].plot(x, np.cos(x), color='#D86175')
axs[0, 1].set_title('cos(x)')
axs[0, 1].set_ylabel('Amplitude')

axs[1, 0].plot(x, np.sin(x)**2, color='#2B8F84')
axs[1, 0].set_title('sin²(x)')
axs[1, 0].set_xlabel('x')
axs[1, 0].set_ylabel('Amplitude')

axs[1, 1].plot(x, np.cos(x)**2, color='#806480')
axs[1, 1].set_title('cos²(x)')
axs[1, 1].set_xlabel('x')
axs[1, 1].set_ylabel('Amplitude')

plt.tight_layout()
plt.show()
```

`plt.subplots(2, 2)` returns a 2D array of `Axes` objects accessed with two indices: `axs[row, col]`. `sharex=True` links the x axes across all subplots so zooming or panning one updates them all — it also suppresses x-axis tick labels on the top row automatically. `plt.tight_layout()` adjusts spacing between panels.

</details>

---

## Well done for completing Unit 4 exercises!

If any section felt difficult, revisit the relevant part of the Unit 4 reading material before moving on.

**Key reminders:**

- `shape` returns a tuple of dimensions; `size` is the total number of elements; `ndim` is the number of axes
- `np.random.seed()` is a function call, not an attribute assignment — always use parentheses
- When casting to a smaller integer type, NumPy truncates rather than rounds — `3.9` becomes `3`, not `4`
- Slices of a NumPy array return **views**, not copies — modifying a view modifies the original; use `.copy()` to avoid this
- Use `|` and `&` for element-wise boolean operations on arrays, never `or` and `and` — and always wrap each condition in parentheses
- `np.nanmean`, `np.nansum`, and `np.nanargmax` ignore `nan` values; the plain versions propagate `nan` through the result
- `axis=0` operates **down** the rows (collapses rows → one value per column); `axis=1` operates **across** columns (collapses columns → one value per row)
- When dividing a 2D array by a 1D row-of-sums, reshape the 1D array to `(-1, 1)` so broadcasting aligns correctly
- `reshape` cannot change the total number of elements; use `-1` to let NumPy infer one dimension automatically
- `ravel()` returns a view when possible; `flatten()` always returns a copy
- `ax.set_title`, `ax.set_xlabel`, and `ax.legend` are methods on the **Axes object** (`ax`), not on `plt`
- Lines only appear in the legend if they were plotted with a `label=` argument